CREATE TABLE [dbo].[Dinosaurs](
	[DinosaurId] [int] IDENTITY(1,1) NOT NULL,
	[DinosaurName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK__Dinosaur__D1F7CD0B13115FCD] PRIMARY KEY CLUSTERED 
(
	[DinosaurId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO